apiVersion: v1
kind: Service
metadata:
  name: kubernetesprobedemo
spec:
  selector:
    app: kubernetesprobedemo
  ports:
  - port: 32001
    nodePort: 32001
    targetPort: 80
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubernetesprobedemo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kubernetesprobedemo
    spec:
      containers:
      - image: jannemattila/kubernetesprobedemo:latest
        name: kubernetesprobedemo
        livenessProbe:
          httpGet:
            path: /api/HealthCheck/Liveness
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 2
        readinessProbe:
          httpGet:
            path: /api/HealthCheck/Readiness
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
