apiVersion: v1
kind: Namespace
metadata:
  name: kubedemo
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetesprobedemo
  namespace: kubedemo
spec:
  selector:
    app: kubernetesprobedemo
  ports:
  - port: 32001
    nodePort: 32001
    targetPort: 80
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetesprobedemo
  namespace: kubedemo
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: kubernetesprobedemo
    spec:
      restartPolicy: Always
      containers:
      - image: kubernetesprobedemo:v1
        imagePullPolicy: IfNotPresent
        name: kubernetesprobedemo
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        livenessProbe:
          httpGet:
            path: /api/HealthCheck/Liveness
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 1
        readinessProbe:
          httpGet:
            path: /api/HealthCheck/Readiness
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 1
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        env:
          - name: webhook
            value: "http://echo:31111/api/echo"
          - name: livenessCheck
            value: "true"
          - name: readinessCheck
            value: "true"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kubernetesprobedemo
  namespace: kubedemo
spec:
  minReplicas: 3
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kubernetesprobedemo
    namespace: kubernetesprobedemo
  targetCPUUtilizationPercentage: 50
